version: "3"

services:

  web:
    image: "ghcr.io/leitosama/m3ss3ng3r:main"
    build: ./project
    restart: always
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8004:8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db_ms:5432/users?sslmode=disable
    depends_on:
      - db_ms

  db_ms:
    image: postgres
    restart: always
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users

