"""commit_name

Revision ID: 18ac3ae28adb
Revises: d68431cca5b5
Create Date: 2022-04-14 19:11:32.242605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18ac3ae28adb'
down_revision = 'd68431cca5b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
