"""commit_name

Revision ID: 207a04fb3bb3
Revises: 18ac3ae28adb
Create Date: 2022-04-14 19:11:36.272627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207a04fb3bb3'
down_revision = '18ac3ae28adb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
