"""commit_name

Revision ID: 657ee6b7dd9b
Revises: bb51cafcedf8
Create Date: 2022-04-14 19:11:26.146626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '657ee6b7dd9b'
down_revision = 'bb51cafcedf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
