"""commit_name

Revision ID: 8e51620e997b
Revises: 657ee6b7dd9b
Create Date: 2022-04-14 19:11:27.132022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e51620e997b'
down_revision = '657ee6b7dd9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
