"""commit_name

Revision ID: bb51cafcedf8
Revises: d69fb924ab81
Create Date: 2022-04-14 19:11:25.219020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb51cafcedf8'
down_revision = 'd69fb924ab81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
