"""commit_name

Revision ID: c39017ce6730
Revises: 8e51620e997b
Create Date: 2022-04-14 19:11:28.277169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c39017ce6730'
down_revision = '8e51620e997b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
