"""commit_name

Revision ID: d68431cca5b5
Revises: c39017ce6730
Create Date: 2022-04-14 19:11:29.834926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd68431cca5b5'
down_revision = 'c39017ce6730'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
