version: "3"

services:

  casic:
    image: "ghcr.io/leitosama/casic:main"
    build: .
    ports:
      - 7777:7777
    restart: always
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"
    restart: always
    environment:
      POSTGRES_USER: casic
      POSTGRES_PASSWORD: casic_password
      POSTGRES_DB: casic
