version: '3.5'

networks:
  default:
    ipam:
      driver: default

services:
  webserver:
    image: ghcr.io/leitosama/merc2022:main@sha256:d5be0b41e5c8cc7148383e51d1eb403b290b9c5e8a453ad8a6675782bd35e837
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DB_PASSWORD
    ports:
      - "6666:80"
    volumes:
      - "./source:/var/www/html"
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:12
    environment:
      POSTGRES_ROOT_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: "merc"
    volumes:
      - "./db.sh:/docker-entrypoint-initdb.d/initdb.sh"
    restart: always

  adminer:
    image: adminer:4.7.8
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - "6667:8080"
    restart: always
