name: Docker merc2022

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'merc2022/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/merc2022


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}


      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: ./merc2022/
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
  
  test-checker:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup python for checker
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install requirements
        run: pip install -r ./merc2022/checker/requirements.txt
      
      - name: docker-compose up
        run: | 
          echo ---Building and starting up docker---
          docker-compose -f ./merc2022/docker-compose.yml up -d
          echo ---Containers up---

      - name: Curl test
        run: |
          curl -vvv http://127.0.0.1:6666  
      
      - name: Run checker check
        run: |
          set +e
          python ./merc2022/checker/checker.py check 127.0.0.1
          exitcode="$?"
          echo "exitcode=$exitcode" 
          if [[ $exitcode -ne "101" ]]; then exit $exitcode; fi
          exit 0
      
      - name: Destroy and clean up
        run: |
          docker-compose -f ./merc2022/docker-compose.yml down --rmi --remove-orphans
      