name: packer

on:
  workflow_dispatch:
  push:
    paths:
      - 'vulnbox.pkr.hcl'
      - '.packer/**'
      - '.github/workflows/packer.yml'

jobs:
  packer:
    runs-on: macos-12
    name: Run Packer
    env:
      PKR_VAR_username: yeti
      PKR_VAR_password: Password123 # TODO: Fix hardcode password pls
      PKR_VAR_event: YetiCTF2022 # TODO: Fix hardcode
      ZIP_PASSWORD: Password123  # TODO: Fix hardcode password pls
      PKR_VAR_services: '["Casic","M3SS3NG3R","SqlOnline","merc2022"]' # TODO: Fix hardcode
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Packer Cache restore
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.config/packer/
            ./packer_cache/
          key: ${{ runner.os }}-packer-

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main

      - run: packer init .
        env:
          PACKER_GITHUB_API_TOKEN: ${{ secrets.PACKER_GITHUB_API_TOKEN }}

      - name: Cache packer config
        uses: actions/cache/save@v3
        with:
          path: ~/.config/packer/
          key: ${{ runner.os }}-packer-${{ hashFiles('vulnbox.pkr.hcl') }}

      - run: packer validate .
        env: 
          PKR_VAR_services: ${{ steps.services.outputs.services }}

      - run: packer build .
        env: 
          PKR_VAR_services: ${{ steps.services.outputs.services }}

      - name: Cache packer cache
        uses: actions/cache/save@v3
        with:
          path: ./packer_cache
          key: ${{ runner.os }}-packer-${{ hashFiles('vulnbox.pkr.hcl') }}
      
      - name: Get current date
        id: today
        run: echo "today=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: ZIP w\ password
        run: zip -e -P $ZIP_PASSWORD ${PKR_VAR_event}_${{ steps.today.outputs.today }}.ova.zip ${PKR_VAR_event}.ova
        working-directory: ./output-vulnbox/

      - name: Put to Yandex Object storage
        run: aws s3 --endpoint-url=https://storage.yandexcloud.net cp --quiet ${PKR_VAR_event}_${{ steps.today.outputs.today }}.ova.zip s3://vulnbox/$PKR_VAR_event_${{ steps.today.outputs.today }}.ova.zip
        working-directory: ./output-vulnbox/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.YC_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.YC_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ru-central1"
