name: packer

on:
  workflow_dispatch:
  push:
    paths:
      - 'vulnbox.pkr.hcl'
      - '.packer/**'
      - '.github/workflows/packer.yml'

jobs:
  packer:
    runs-on: macos-12
    name: Run Packer
    env:
      PKR_VAR_username: yeti
      PKR_VAR_password: Password123 # TODO: Fix hardcode password pls
      PKR_VAR_event: YetiCTF2022 # TODO: Fix hardcode
      ZIP_PASSWORD: Password123  # TODO: Fix hardcode password pls
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main

      - name: packer init & validate
        run: |
          packer init .
          packer validate .
        env:
          PACKER_GITHUB_API_TOKEN: ${{ secrets.PACKER_GITHUB_API_TOKEN }}
          PKR_VAR_vagrantbox: ${{ steps.vm-name.outputs.vm_name }}

      - name: packer build .
        run: packer build .
        env:
          PACKER_GITHUB_API_TOKEN: ${{ secrets.PACKER_GITHUB_API_TOKEN }}

      - name: Get current date
        id: today
        run: echo "today=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: ZIP w\ password
        run: zip -e -P $ZIP_PASSWORD ${PKR_VAR_event}_${{ steps.today.outputs.today }}.ova.zip ${PKR_VAR_event}.ova
        working-directory: ./.vulnbox/output-vulnbox/

      - name: Put to Yandex Object storage
        run: aws s3 --endpoint-url=https://storage.yandexcloud.net cp --quiet ${PKR_VAR_event}_${{ steps.today.outputs.today }}.ova.zip s3://vulnbox/$PKR_VAR_event_${{ steps.today.outputs.today }}.ova.zip
        working-directory: ./.vulnbox/output-vulnbox/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.YC_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.YC_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ru-central1"
